[package]
name = "autograph"
version = "0.0.4"
authors = ["Charles R Earp <charles.r.earp@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
description = "Deep Neural Network Library for Rust"
homepage = "https://github.com/charles-r-earp/autograph"
repository = "https://github.com/charles-r-earp/autograph"
keywords = ["neural-networks", "machine-learning", "cuda", "deep-learning", "autograd"]
categories = ["science"]
readme = "README.md"
publish = false

[features]
# Dev use only / Shaders are shipped with the crate
# GLSL compilation does not work on Windows
compile-shaders = []

[dependencies]
wgpu = "0.6.0"
proxy-enum = "0.3.0"
bytemuck = { version = "1.4.1", features = ["derive"] }
ndarray = "0.14.0"
smol = "1.2.5"
dashmap = "3.11.10"
rspirv = "0.7.0"
serde = { version = "1.0.118", features = ["derive"] }
ahash = "0.6.1"
num-traits = "0.2.14"

[dev-dependencies]
approx = "0.4.0"
criterion = "0.3.3"
rstest = "0.6.4"

[[bench]]
name = "benchmarks"
harness = false




