[package]
name = "autograph"
version = "0.0.4"
authors = ["Charles R Earp <charles.r.earp@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
description = "Deep Neural Network Library for Rust"
homepage = "https://github.com/charles-r-earp/autograph"
repository = "https://github.com/charles-r-earp/autograph"
keywords = ["neural-networks", "machine-learning", "deep-learning", "autograd", "gpu"]
categories = ["science"]
readme = "README.md"
publish = false

[features]
derive = ["autograph_derive"]

[dependencies]
autograph_derive = { path = "autograph_derive", optional = true }
#proxy-enum = "0.3.1"
bytemuck = { version = "1.4.1", features = ["derive"] }
ndarray = { version = "0.14.0", features = ["approx", "serde"] }
smol = "1.2.5"
rspirv = "0.7.0"
serde = { version = "1.0.126", features = ["derive", "rc"] }
num-traits = "0.2.14"
half = { version = "1.7.1", features=["num-traits", "bytemuck", "serde"] }
gfx-hal = "0.9.0"
hibitset = "0.6.3"
anyhow = "1.0.37"
thiserror = "1.0.23"
derive_more = "0.99.11"
#dirs = "3.0.1"
#downloader = "0.2.0"
#http = "0.2.3"
#futures-channel = "0.3.11"
#rand = "0.8.2"
#futures-util = "0.3.11"
#indicatif = "0.15.0"
rand_distr = "0.4.0"
#flate2 = "1.0.20"
#byteorder = "1.4.3"
lazy_static = "1.4.0"
#bincode = "1.3.3"
#futures-core = "0.3.15"
crossbeam-utils = "0.8.5"
once_cell = "1.8.0"
parking_lot = "0.11.1"
crossbeam-channel = "0.5.1"
tinyvec = "1.2.0"
bincode = "1.3.3"
tokio = { version = "1.8.1", features = ["full"] }

[target."cfg(all(unix, not(target_os = \"ios\"), not(target_os = \"macos\")))".dependencies]
gfx-backend-vulkan = "0.9.0"

[target."cfg(any(target_os = \"ios\", target_os = \"macos\"))".dependencies]
gfx-backend-vulkan = { version = "0.9.0", optional = true }
gfx-backend-metal = "0.9.0"

[target."cfg(windows)".dependencies]
gfx-backend-vulkan = "0.9.0"
gfx-backend-dx12 = "0.9.0"

[dev-dependencies]
approx = "0.4.0"
criterion = "0.3.3"
tokio = { version = "1.8.1", features = ["full"] }

[build-dependencies]
rspirv = "0.7.0"
bytemuck = "1.7.0"
anyhow = "1.0.42"
lazy_static = "1.4.0"
serde = { version = "1.0.126", features = ["derive"] }
hibitset = "0.6.3"
parking_lot = "0.11.1"
walkdir = "2.3.2"
bincode = "1.3.3"
