[package]
name = "autograph"
version = "0.0.4"
authors = ["Charles R Earp <charles.r.earp@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
description = "Deep Neural Network Library for Rust"
homepage = "https://github.com/charles-r-earp/autograph"
repository = "https://github.com/charles-r-earp/autograph"
keywords = ["neural-networks", "machine-learning", "cuda", "deep-learning", "autograd"]
categories = ["science"]
readme = "README.md"
publish = false

[features]
# Dev use only / Shaders are shipped with the crate
# GLSL compilation does not work on Windows
compile-shaders = []

[dependencies]
proxy-enum = "0.3.0"
bytemuck = { version = "1.4.1", features = ["derive"] }
ndarray = { version = "0.14.0", features = ["approx"] }
smol = "1.2.5"
rspirv = "0.7.0"
serde = { version = "1.0.118", features = ["derive"] }
num-traits = "0.2.14"
half = { git = "https://github.com/charles-r-earp/half-rs", features = ["bytemuck", "num-traits"] }
gfx-hal = "0.6.0"
futures = "0.3.8"
hibitset = "0.6.3"
anyhow = "1.0.37"
thiserror = "1.0.23"
derive_more = "0.99.11"

[target."cfg(all(unix, not(target_os = \"ios\"), not(target_os = \"macos\")))".dependencies]
gfx-backend-vulkan = "0.6.5"

[target."cfg(any(target_os = \"ios\", target_os = \"macos\"))".dependencies]
gfx-backend-vulkan = { version = "0.6.5", optional = true }
gfx-backend-metal = "0.6"

[target."cfg(windows)".dependencies]
gfx-backend-vulkan = "0.6.5"
gfx-backend-dx12 = "0.6"

[dev-dependencies]
approx = "0.4.0"
criterion = "0.3.3"

[[bench]]
name = "benchmarks"
harness = false




