name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: macos-latest
            target: x86_64-apple-darwin
    steps:
    - uses: actions/checkout@v2
    - name: cargo fetch
      run: cargo fetch --target ${{ matrix.target }}
    - name: Check
      run: cargo check --tests --lib --benches
    - name: Check KMeans Iris Example
      run: cd examples/cluster/kmeans/iris && cargo check && cargo check --features plotters
    - name: Check NeuralNetwork MNIST Example 
      run: cd examples/neural_network/mnist && cargo check
    - name: Test
      run: RUST_BACKTRACE=1 cargo test --no-fail-fast -- --test-threads 1
    - name: Test Benchmarks
      run: cargo test --benches
    - name: Test KMeans Iris Example
      if: ${{ matrix.os == 'windows-latest' }}
      run: cd examples/cluster/kmeans/iris && cargo run && cargo run --features plotters
    - name: Test NeuralNetwork MNIST Example
      if: ${{ matrix.os == 'windows-latest' }}
      run: cd examples/neural_network/mnist && cargo run
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install rustup components
        run: rustup component add rustfmt clippy
      - name: Rustfmt
        run: cargo fmt --all -- --check
      - name: cargo fetch
        run: cargo fetch
      - name: Clippy
        run: RUSTFLAGS="-Dwarnings" cargo clippy -- -D warnings
