
name: Continuous Integration

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ${{ matrix.os }}
    env:
      RUST_BACKTRACE: 1
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            features: full
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            features: "full device_tests"
          - os: macos-latest
            target: x86_64-apple-darwin
            features: full
    steps:
    - uses: actions/checkout@v2
    - name: cargo fetch
      run: cargo fetch --target ${{ matrix.target }}
    - name: Check
      run: cargo check --tests --lib --benches --features full
    - name: Test 
      run: cargo test --features "${{ matrix.features }}"
    - name: Test Atomics
      if: ${{ matrix.os == 'windows-latest' }}
      continue-on-error: true
      run: cargo test --features "full device_tests" atomic_add_f32 -- --ignored
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install rustup components
        run: rustup component add rustfmt clippy
      - name: Rustfmt
        run: cargo fmt --all -- --check
      - name: cargo fetch
        run: cargo fetch
      - name: Clippy
        run: RUSTFLAGS="-Dwarnings" cargo clippy -- -D warnings
