
name: Continuous Integration

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ${{ matrix.os }}
    env:
      RUST_BACKTRACE: 1
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: macos-latest
            target: x86_64-apple-darwin
    steps:
    - uses: actions/checkout@v2
    - name: cargo fetch
      run: cargo fetch --target ${{ matrix.target }}
    - name: Build
      run: cargo build --all-features --all-targets
      continue-on-error: true
    - name: Test 
      run: cargo test --no-default-features 
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install rustup components
        run: rustup component add rustfmt clippy
      - name: Rustfmt
        run: cargo fmt --all -- --check
        continue-on-error: true
      - name: Clippy
        run: cargo clippy --no-default-features --features "neural-network" -- -D warnings
        continue-on-error: true
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-04-15
          components: rust-src, rustc-dev, llvm-tools-preview
      - name: install krnlc
        run: cargo +nightly-2023-04-15 install krnlc --git=https://github.com/charles-r-earp/krnl --locked -v
      - name: krnlc
        run: krnlc -p autograph -v --check
