name: Continuous Integration

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ${{ matrix.os }}
    env:
      RUST_BACKTRACE: 1
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
    steps:
    - uses: actions/checkout@v2
    - name: cargo fetch
      run: cargo fetch --target ${{ matrix.target }}
    - name: Test Device New
      run: cargo check --features device_tests
